### ISSUE TITLE
can't detect vapoursynth

### ISSUE THREAD

**Issue by sl1pkn07** [dwbuiten/d2vsource#19]
build log http://sl1pkn07.wtf/paste/view/52263c4e

VS version  6a7ca02a87feb9975f1188a9f6e18db4d37dae53

EDIT: removed useless check log

**Comment by dwbuiten** [comment]
Seemed to work when I tested that. Can you try with this: https://github.com/dwbuiten/d2vsource/issues/12

**Comment by sl1pkn07** [comment]
the problem is not that fail check . is not add the headers path in the cxxflags

**Comment by 4re** [comment]
https://github.com/dwbuiten/d2vsource/pull/18 should fix this, the configure script doesn't actually adds the headers anywhere.

**Comment by dwbuiten** [comment]
Yes, hence why I asked @sl1pkn07 to actually test the patch.

**Comment by 4re** [comment]
but you linked a bug report number 12 :P

**Comment by sl1pkn07** [comment]
yes, https://github.com/dwbuiten/d2vsource/pull/18 fix my issue

**Comment by dwbuiten** [comment]
Woops. That's my own incompetence there. Yeah, I meant #18.

Thanks!
