### ISSUE TITLE
Should set nfMakeLinear flag when being compiled for R30 and newer

### ISSUE THREAD

**Issue by myrsloik** [dwbuiten/d2vsource#21]

**Comment by dwbuiten** [comment]
I mean, I could just set it regardless, and required new VS?

**Comment by myrsloik** [comment]
That also works

**Comment by myrsloik** [comment]
But maybe wait until R30 is actually released in that case

**Comment by dwbuiten** [comment]
Because I'm so fast at working on d2vsource.
