### ISSUE TITLE
Output is faded compared to ffms2

### ISSUE THREAD

**Issue by Noctem** [dwbuiten/d2vsource#28]
I've only tested this with one video so far, but I noticed that the colors I got with d2vsource are noticeably duller than ffms2. Is there a reason for that? VapourSynth Editor reports that the format is YUV422P8 for both of them.

`c.d2v.Source(input=r'video.d2v')`
![example-d2vsource](https://cloud.githubusercontent.com/assets/1787524/15556626/1250f412-228c-11e6-832e-3c81fc564f34.png)

`c.ffms2.Source(source="video.ts")`
![example-ffms2](https://cloud.githubusercontent.com/assets/1787524/15556625/124fa4e0-228c-11e6-80b3-3b451c3bdd5a.png)

**Comment by dubhater** [comment]
You must have ``YUVRGB_Scale=1`` in the d2v file. It means that d2vsource will mark the frames as full range YUV. Either change that to 0, or add ``clip = c.std.SetFrameProp(clip, prop="_ColorRange", intval=1)`` right after the source filter. (Yes, the values for YUVRGB_Scale and the _ColorRange property are backwards.)

If you created the d2v file with dgindex, there is an option in one of the menus where you can pick the colour range. If you created it with d2vwitch, there is no way to pick the colour range (yet).

http://rationalqm.us/dgmpgdec/DGIndexManual.html#AppendixA
http://www.vapoursynth.com/doc/apireference.html#reserved-frame-properties
http://www.vapoursynth.com/doc/functions/setframeprop.html

**Comment by Noctem** [comment]
Excellent, thanks. Setting `YUVRGB_Scale` to `0` fixed it. I should have checked on that.
