### ISSUE TITLE
building on MacOS X 10.11.6

### ISSUE THREAD

**Issue by Selur** [dwbuiten/d2vsource#30]
trying to build the filter on Mac OS X I end up without  a dylib file

> Selurs-Mac-mini:d2vsource selur$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
glibtoolize: and rerunning glibtoolize and aclocal.
glibtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:8: installing './compile'
configure.ac:8: installing './config.guess'
configure.ac:8: installing './config.sub'
configure.ac:5: installing './install-sh'
configure.ac:5: installing './missing'
Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
Selurs-Mac-mini:d2vsource selur$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin15.6.0 file names to x86_64-apple-darwin15.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin15.6.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libavcodec... yes
checking for libavformat... yes
checking for libavutil... yes
checking for VapourSynth... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
Selurs-Mac-mini:d2vsource selur$ make
  CXX      src/core/compat.lo
  CXX      src/core/d2v.lo
  CXX      src/core/decode.lo
src/core/decode.cpp:450:45: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                if (dctx->fctx->streams[i]->codec->codec_type == AVMEDIA_TYPE_VIDEO)
                                            ^
/usr/local/Cellar/ffmpeg/3.1.3/include/libavformat/avformat.h:880:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
src/core/decode.cpp:491:13: warning: 'avcodec_decode_video2' is deprecated [-Wdeprecated-declarations]
            avcodec_decode_video2(dctx->avctx, out, &av_ret, &dctx->inpkt);
            ^
/usr/local/Cellar/ffmpeg/3.1.3/include/libavcodec/avcodec.h:4753:5: note: 'avcodec_decode_video2' has been explicitly marked deprecated here
int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
    ^
/usr/local/Cellar/ffmpeg/3.1.3/include/libavcodec/avcodec.h:1557:16: warning: 'convergence_duration' is deprecated [-Wdeprecated-declarations]
typedef struct AVPacket {
               ^
/usr/local/Cellar/ffmpeg/3.1.3/include/libavcodec/avcodec.h:1609:13: note: 'convergence_duration' has been explicitly marked deprecated here
    int64_t convergence_duration;
            ^
src/core/decode.cpp:510:25: warning: 'avcodec_decode_video2' is deprecated [-Wdeprecated-declarations]
                int r = avcodec_decode_video2(dctx->avctx, out, &av_ret, &dctx->inpkt);
                        ^
/usr/local/Cellar/ffmpeg/3.1.3/include/libavcodec/avcodec.h:4753:5: note: 'avcodec_decode_video2' has been explicitly marked deprecated here
int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
    ^
/usr/local/Cellar/ffmpeg/3.1.3/include/libavcodec/avcodec.h:1557:16: warning: 'convergence_duration' is deprecated [-Wdeprecated-declarations]
typedef struct AVPacket {
               ^
/usr/local/Cellar/ffmpeg/3.1.3/include/libavcodec/avcodec.h:1609:13: note: 'convergence_duration' has been explicitly marked deprecated here
    int64_t convergence_duration;
            ^
/usr/local/Cellar/ffmpeg/3.1.3/include/libavcodec/avcodec.h:1557:16: warning: 'convergence_duration' is deprecated [-Wdeprecated-declarations]
typedef struct AVPacket {
               ^
/usr/local/Cellar/ffmpeg/3.1.3/include/libavcodec/avcodec.h:1609:13: note: 'convergence_duration' has been explicitly marked deprecated here
    int64_t convergence_duration;
            ^
6 warnings generated.
  CXX      src/vs/applyrff.lo
  CXX      src/vs/d2vsource.lo
  CXX      src/vs/directrender.lo
  CXX      src/vs/vapoursynth.lo
  CXXLD    libd2vsource.la

am I missing something or is this a bug?

**Comment by dubhater** [comment]
``ls .libs``

**Comment by Selur** [comment]
Thanks,...

**Comment by dwbuiten** [comment]
Or just use `--prefix=/my/path` when configuring `make install` like in every other autotools system.
