### ISSUE TITLE
OSX Compile Issue

### ISSUE THREAD

**Issue by l33tmeatwad** [dwbuiten/d2vsource#33]
The way push_back is used in applyrff (between lines 193 to 211) seem to cause issues with compiling on OSX.

src/vs/applyrff.cpp:192:36: error: expected expression
            data->fields.push_back({ i, Progressive });
                                   ^
src/vs/applyrff.cpp:193:36: error: expected expression
            data->fields.push_back({ i, Progressive });
                                   ^
src/vs/applyrff.cpp:196:40: error: expected expression
                data->fields.push_back({ i, Progressive });
                                       ^
src/vs/applyrff.cpp:197:40: error: expected expression
                data->fields.push_back({ i, Progressive });
                                       ^
src/vs/applyrff.cpp:200:44: error: expected expression
                    data->fields.push_back({ i, Progressive });
                                           ^
src/vs/applyrff.cpp:201:44: error: expected expression
                    data->fields.push_back({ i, Progressive });
                                           ^
src/vs/applyrff.cpp:207:36: error: expected expression
            data->fields.push_back({ i, tff ? Top : Bottom });
                                   ^
src/vs/applyrff.cpp:208:36: error: expected expression
            data->fields.push_back({ i, tff ? Bottom : Top });
                                   ^
src/vs/applyrff.cpp:211:40: error: expected expression
                data->fields.push_back({ i, tff ? Top : Bottom });
                                       ^

**Comment by dubhater** [comment]
Must be that C++11. Try it now.

**Comment by l33tmeatwad** [comment]
That patched it, thanks!
