### ISSUE TITLE
"Invalid location" for valid Location offsets

### ISSUE THREAD

**Issue by Gebbi** [dwbuiten/d2vsource#34]
"Invalid location in D2V header" can be triggered for valid Location offsets in certain situations.

Example:
`Location=4,68350,6,34ff4`

This is valid (start file < end file, so naturally start offset < end offset) and works in AviSynth with Mpeg2Source.

It triggers the following check in core/d2v.cpp:

`if (ret->loc.startfile < 0 || ret->loc.startoffset < 0 ||
               ret->loc.endfile < ret->loc.startfile || ret->loc.endoffset < ret->loc.startoffset) {
        err = "Invalid location in D2V header."; goto fail;
    }`

The start/end files are not considered for `ret->loc.endoffset < ret->loc.startoffset`, so it throws an error in this case, because 34ff4 < 68350, even though 34ff4 is the offset for file 6.

**Comment by dubhater** [comment]
The funny thing is that the Location line is otherwise completely ignored.
