### ISSUE TITLE
Field Operation's aren't working correctly

### ISSUE THREAD

**Issue by rlaPHOENiX** [dwbuiten/d2vsource#39]
![image](https://user-images.githubusercontent.com/17136956/71638141-c22d2b00-2c4f-11ea-8362-7a95f66e65e1.png)
~~_MPEG-2 @ 24000/1001 Progressive (2:3 Pulldown)_~~
_* edit: It's actually MPEG-2 @ 30000/1001 (Hard-Telecine that used 2:3 Pulldown) Progressive with some sections being Interlaced, this specific screenshot is of an unnecessary frame caused by Hard-Telecine_
This screenshot is from Family Guy Volume 1 Disc 1 Episode 1.

~~As you can see, it is showing interlacing very very frequently.
It's like this for both "Honor Pulldown Flags" and "Ignore Pulldown Flags" Field Operations.
It's frame count, duration and fps all seems accurate, yet when I play it, it seems super choppy and slower than it should be.~~

If I set `rff=False` on either Field Operation, no interlacing occurs, but its out of sync, the duration drops from 22:30~ to 18:29, yet somehow feels accurate in terms of motion speed and such. If I use AssumeFPS to set it to 24000/1001 (original FPS) it results in 23:06 duration and feels super slow and choppy.

1. `rff=False` = no interlacing e.t.c, but the FPS is still 30000/1001
2. core.std.AssumeFPS to whatever the framerate was meant to be (in my case 24000/1001 as it used 2:3 Pulldown)
3. Preview in vs-edit and it feels slow for some really odd reason, it feels like you stretched the footage or something, but...
4. If you create an encode and mux the audio in to make sure everything lines up, everything feels fine and syncs up, it's an odd issue.

**Comment by dwbuiten** [comment]
This sounds like expected behavior, unless I am misreading.

Does the official DGIndex reader (for AviSynth) behave in some other way?

**Comment by rlaPHOENiX** [comment]
So after re-checking and research I found out that this is in fact all expected behavior I apologize for the waste of time.

However I will make some notes in case someone is here and confused like me:

1. Rff is Repeated Fields First, essentially A toggle switch for any Pulldown used. When setting this to False on a 30000/1001 encoded video, it will still return 30000/1001 hence my initial confusion, but this is in fact accurate because it is actually 30000/1001, the video itself is telecined to 30000/1001 (Hard-Telecine), but settings rff=False, and manually assuming fps to 24000/1001 (if Pulldown 2:3 on a 30000/1001 video for ex), will result in IVTC'd soft-telecined source. All of this operation is expected.

**Comment by rlaPHOENiX** [comment]
@dwbuiten is everything I say here on my post right above correct? The only thing i'm a bit confused on still, is exactly how rff=False is working since the content itself is encoded at 30000/1001, so the pulldown isn't a flag sort of pulldown.
